### ISSUE TITLE
Add Tracy\Tracy for easier local development

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/rector-ci#24]

**Comment by TomasVotruba** [comment]
Like in composer.json? Why not just add it? :D

**Comment by JanMikes** [comment]
Well, add it and configure with monolog 😄

**Comment by TomasVotruba** [comment]
Ok. Just add it when you need it, these small issues make it hard to prioritize

**Comment by JanMikes** [comment]
Why are you just randomly closing my issues? 😢 You are closing issues only because you prefer different way of using them.

2 people = 2 opinions and preferences

**Comment by TomasVotruba** [comment]
Indeed, let's talk about in person tomorrow.
