### ISSUE TITLE
Add per rule commiting feature

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-ci#42]
Imagine there is PHP 8.0 set and everything is committed in one go. 30 rules with one commit. Very hard to rebase or modify.
In small code bases it cold be ok, but in practice it easier to work with smaller chunks.

Based on talk with @jfrnl

**Comment by JanMikes** [comment]
Great feedback, thank you 👍

**Comment by JanMikes** [comment]
Added low priority label - we will start with 1 commit for the whole set and will wait for feedback.

**Comment by TomasVotruba** [comment]
Closing as outdated
